traiterJson({
"trait":1,
"scoreJ":83,
"scoreJ5":121,
"scoreR":0,
"scoreR5":0,
"bonusJ":1,
"malusJ":5,
"bonusR":0,
"malusR":4,
"cols": [
	 {"nb":1, "couleur":2},
	 {"nb":1, "couleur":1},
	 {"nb":1, "couleur":2},
	 {"nb":1, "couleur":1},
	 {"nb":1, "couleur":2},
	 {"nb":1, "couleur":1},
	 {"nb":1, "couleur":1},
	 {"nb":1, "couleur":2},
	 {"nb":1, "couleur":1},
	 {"nb":1, "couleur":2},
	 {"nb":1, "couleur":1},
	 {"nb":1, "couleur":2},
	 {"nb":1, "couleur":2},
	 {"nb":1, "couleur":1},
	 {"nb":1, "couleur":2},
	 {"nb":1, "couleur":1},
	 {"nb":1, "couleur":2},
	 {"nb":1, "couleur":1},
	 {"nb":1, "couleur":2},
	 {"nb":1, "couleur":1},
	 {"nb":1, "couleur":2},
	 {"nb":1, "couleur":1},
	 {"nb":1, "couleur":2},
	 {"nb":1, "couleur":1},
	 {"nb":1, "couleur":1},
	 {"nb":1, "couleur":2},
	 {"nb":1, "couleur":1},
	 {"nb":1, "couleur":2},
	 {"nb":1, "couleur":1},
	 {"nb":1, "couleur":2},
	 {"nb":1, "couleur":1},
	 {"nb":1, "couleur":2},
	 {"nb":1, "couleur":1},
	 {"nb":1, "couleur":2},
	 {"nb":1, "couleur":1},
	 {"nb":1, "couleur":2},
	 {"nb":1, "couleur":2},
	 {"nb":1, "couleur":1},
	 {"nb":1, "couleur":2},
	 {"nb":1, "couleur":1},
	 {"nb":1, "couleur":2},
	 {"nb":1, "couleur":1},
	 {"nb":1, "couleur":1},
	 {"nb":1, "couleur":2},
	 {"nb":1, "couleur":1},
	 {"nb":1, "couleur":2},
	 {"nb":1, "couleur":1},
	 {"nb":1, "couleur":2},
]
});